development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://vfeafpuetgumpl:328ce7a346337145c8e2a3e9b3ef858ffa17c27caa195e10710ac9d6fd5b2875@ec2-54-83-46-116.compute-1.amazonaws.com:5432/d16deap57jrlp7
  channel_prefix: microversescooters_production
